
import React, { useState } from 'react';
import { Database, Code, Server, Cpu, Layers, Terminal, Workflow } from 'lucide-react';
import GamificationEngine from './GamificationEngine';
import ArchitectureView from './ArchitectureView';

interface Props { theme: 'dark' | 'light'; }

const SystemInfo: React.FC<Props> = ({ theme }) => {
  const [activeTab, setActiveTab] = useState('arch');
  const isDark = theme === 'dark';

  const sections = [
    { id: 'arch', label: 'Arquitetura', icon: Workflow, component: ArchitectureView },
    { id: 'engine', label: 'AI Sandbox', icon: Cpu, component: GamificationEngine },
    { id: 'stack', label: 'Stack Técnica', icon: Layers, component: () => (
      <div className="space-y-6">
        <h4 className="font-bold text-lg uppercase italic tracking-tight">System Technical Stack</h4>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[
            { name: 'Frontend Framework', tech: 'React 19 (ESM Mode)', icon: Code, desc: 'Componentização baseada em hooks e performance otimizada.' },
            { name: 'Styling Engine', tech: 'Tailwind CSS 3.4', icon: Layers, desc: 'Sistema de design utility-first para UI cyberpunk responsiva.' },
            { name: 'AI Models', tech: 'Gemini 3 Flash & 2.5 Image', icon: Cpu, desc: 'Processamento de linguagem natural e geração de mídia multimodal.' },
            { name: 'Data Management', tech: 'TypeScript 5.8 (Strict)', icon: Database, desc: 'Tipagem forte para garantir integridade dos cálculos de RPG.' }
          ].map(item => (
            <div key={item.name} className="flex items-start gap-4 p-6 rounded-2xl bg-slate-900/50 border border-slate-800 group hover:border-blue-500/50 transition-all">
              <div className="bg-blue-600/10 p-3 rounded-xl">
                <item.icon className="w-5 h-5 text-blue-500" />
              </div>
              <div>
                <p className="text-xs font-black text-slate-500 uppercase tracking-widest">{item.name}</p>
                <p className="font-black text-blue-400 mt-1">{item.tech}</p>
                <p className="text-xs text-slate-500 mt-2 leading-relaxed">{item.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    )},
    { id: 'db', label: 'Modelos de Dados', icon: Database, component: () => (
      <div className="space-y-6">
        <h4 className="font-bold text-lg uppercase italic tracking-tight">Core RPG Data Models</h4>
        <div className="font-mono text-[10px] space-y-4">
          <div className="p-6 bg-black rounded-2xl border border-slate-800">
            <p className="text-emerald-500">// Perfil do Herói</p>
            <p className="text-blue-400 font-bold">TABLE users {`{`}</p>
            <p className="pl-4">id uuid [pk]</p>
            <p className="pl-4">email varchar [unique]</p>
            <p className="pl-4">combat_power int [default: 0]</p>
            <p className="pl-4">funits_balance int [default: 0]</p>
            <p className="pl-4">phase int [default: 1]</p>
            <p className="pl-4">metadata jsonb // badges, current_streak</p>
            <p className="text-blue-400 font-bold">{`}`}</p>
          </div>
          <div className="p-6 bg-black rounded-2xl border border-slate-800">
            <p className="text-emerald-500">// Log de Batalhas (Treinos)</p>
            <p className="text-blue-400 font-bold">TABLE workouts {`{`}</p>
            <p className="pl-4">id uuid [pk]</p>
            <p className="pl-4">user_id fk -&gt; users.id</p>
            <p className="pl-4">type enum ['SCOUT', 'SKIRMISH', 'BOSS']</p>
            <p className="pl-4">stats jsonb // distance, pace, elevation</p>
            <p className="pl-4">narrative_report text // Generated by Gemini</p>
            <p className="text-blue-400 font-bold">{`}`}</p>
          </div>
        </div>
      </div>
    )},
  ];

  return (
    <div className="space-y-8 pb-12 animate-in fade-in duration-700">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4 border-b border-slate-800 pb-8">
        <div>
          <h2 className="text-3xl font-black italic uppercase flex items-center gap-3">
            <Terminal className="text-blue-500 w-8 h-8" /> Funpace Terminal
          </h2>
          <p className="text-xs font-black text-slate-500 uppercase mt-1 tracking-widest">System Documentation & Performance Monitor</p>
        </div>
        <div className="flex items-center gap-4 bg-slate-900 px-6 py-2 rounded-full border border-slate-800">
           <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
           <span className="text-[10px] font-black uppercase text-emerald-500">System Healthy</span>
        </div>
      </div>

      <div className="flex gap-2 overflow-x-auto scrollbar-hide py-2">
        {sections.map(tab => (
          <button 
            key={tab.id} 
            onClick={() => setActiveTab(tab.id)} 
            className={`flex items-center gap-2 px-6 py-4 rounded-2xl border font-black text-[10px] uppercase tracking-widest transition-all flex-shrink-0 ${
              activeTab === tab.id 
                ? 'bg-blue-600 border-blue-600 text-white shadow-xl shadow-blue-500/20 scale-105' 
                : 'border-slate-800 bg-slate-900/40 text-slate-500 hover:border-slate-600'
            }`}
          >
            <tab.icon className="w-4 h-4" />
            {tab.label}
          </button>
        ))}
      </div>

      <div className={`p-10 border rounded-[3.5rem] ${isDark ? 'bg-slate-900/40 border-slate-800 shadow-inner' : 'bg-white border-slate-200'}`}>
        {sections.map(tab => tab.id === activeTab && <tab.component key={tab.id} />)}
      </div>
    </div>
  );
};

export default SystemInfo;
